### ISSUE TITLE
create_reference_cov.py file error

### ISSUE THREAD

**Issue by mercywilliams160896** [fredsanto/coverageMaster#10]
I have been attempting to create a reference file using the create_reference_cov.py script. I followed these steps:

I created a cov folder and placed both *.cov and *.report.txt files appropriately within it.

Next, I used the create_reference_cov.py script, providing the path to the cov folder as well as the path to the output folder.

The script runs without any errors; however, it only generates total_chr$.res files with no entries in them. I am encountering this issue, and your assistance in resolving it would be greatly appreciated. Thank you.

**Comment by mercywilliams160896** [comment]
> I have been attempting to create a reference file using the create_reference_cov.py script. I followed these steps:
> 
> I created a cov folder and placed both *.cov and *.report.txt files appropriately within it.
> 
> Next, I used the create_reference_cov.py script, providing the path to the cov folder as well as the path to the output folder.
> 
> The script runs without any errors; however, it only generates total_chr$.res files with no entries in them. I am encountering this issue, and your assistance in resolving it would be greatly appreciated. Thank you.

This is how my  *.cov and *.report.txt file looks

**cov file**
chr1	65565	2
chr1	65566	2
chr1	65567	2
chr1	65568	2
chr1	65569	2
chr1	65570	2
chr1	65571	2
chr1	65572	2
chr1	65573	2
chr1	69037	191

**report.txt**
49498977 + 423753 in total (QC-passed reads + QC-failed reads)
49439137 + 423753 primary
0 + 0 secondary
59840 + 0 supplementary
3778 + 0 duplicates
0 + 0 primary duplicates
49449410 + 0 mapped (99.90% : 0.00%)
49389570 + 0 primary mapped (99.90% : 0.00%)
49439137 + 423753 paired in sequencing
24762484 + 168961 read1
24676653 + 254792 read2
48863122 + 0 properly paired (98.83% : 0.00%)
49022106 + 0 with itself and mate mapped
367464 + 0 singletons (0.74% : 0.00%)
87664 + 0 with mate mapped to a different chr
61559 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by fredsanto** [comment]
It was a missing .decode in the script. Now it is fixed. please rerun it
