### ISSUE TITLE
Is this applicable to plant genomes?

### ISSUE THREAD

**Issue by Huangwenxuan666888** [fredsanto/coverageMaster#11]
Hello. 
In TOOLS/create_reference_cov.py, the human genome format is used. If I want to use the genome of other plants, is it necessary to change the parameters? 
Thanks very much.

**Comment by fredsanto** [comment]
Yes. It is necessary. CoverageMaster (CM) uses human gene references (chr start end exon start end etc..).
You must be able to find the equivalent refrences for your plant of interest to use CM
