### ISSUE TITLE
Matplotlib package issue

### ISSUE THREAD

**Issue by prabirsh** [fredsanto/coverageMaster#2]
Hi, 
covrageMaster - I'm facing with package issue while running the script (coverageMaster.py)..

I have installed all required packages mentioned in the manual, When I tried to run the coverageMaster.py script, while running it was throwing a package issue: Matplotlib requires numpy>=1.17, but the user manual mentioned numpy version should be 1.16.2...

![coverageMaster_error](https://user-images.githubusercontent.com/70584888/177694514-b489821a-d48d-46ac-ab1b-c0d022736eeb.png)

Kindly help us in providing a solution for above version issue.

**Comment by fredsanto** [comment]
Which Matlab version do you have?
Either you upgrade your Numpy or you downgrade your Matlab (IMO first option is better).
