### ISSUE TITLE
docker build issue

### ISSUE THREAD

**Issue by fjmuzengyiheng** [fredsanto/coverageMaster#3]
hi, thank you for providing this first-tier tool coverageMaster.
I am trying to install using Docker according to your instruction:

> cd coverageMasterfolder (i.e. where coverageMaster.py is)
> docker build -t coveragemaster .

but an error occured:

Sending build context to Docker daemon  73.37MB
Step 1/4 : FROM python:3.7-slim
 ---> 1c3e07edea3f
Step 2/4 : RUN pip3 install numpy==1.16.2 sympy==1.0 PyWavelets==1.0.3 matplotlib==2.2.3 scipy==1.2.1 more_itertools==8.8.0 pandas==1.0.0
 ---> Running in 7b24dc958fad
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffb55e2110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/numpy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffb55e27d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/numpy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffb55e2c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/numpy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffb55e2dd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/numpy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffb5100410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/numpy/
ERROR: Could not find a version that satisfies the requirement numpy==1.16.2 (from versions: none)
ERROR: No matching distribution found for numpy==1.16.2
The command '/bin/sh -c pip3 install numpy==1.16.2 sympy==1.0 PyWavelets==1.0.3 matplotlib==2.2.3 scipy==1.2.1 more_itertools==8.8.0 pandas==1.0.0' returned a non-zero code: 1

Could you please help me with this? Thank you so much. : )

**Comment by fredsanto** [comment]
It is fixed now
