### ISSUE TITLE
Reference COV file ISSUE

### ISSUE THREAD

**Issue by andrewdg98** [fredsanto/coverageMaster#5]
Hi, I'm very thankful for your work I'm trying to use coverageMaster after I read your paper. 
I'm not able to create a reference following your instructions. 
I created a COV_folder containing for each sample (I have just 3 but I think it should work anyways) the sampleID.cov and sampleID.report.txt files and an empty folder to use as output. Even if everything seems to be correct the output of the command it's:

 File "/home/andrewdg/jupyter/CoverageMaster/coverageMaster-master/TOOLS/create_reference_cov.py", line 29, in <module>
    l = file.readline().decode("UTF-8")
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

I don't know if the problem it's the number of samples used or if I'm doing something else wrong.
Thank you again and I hope you'll have time to help me

**Comment by fredsanto** [comment]
The script was "inherdited" from a python2.7 version. Now it's python3 compliant.
