### ISSUE TITLE
create_reference_cov.py: NameError: name 'l' is not defined

### ISSUE THREAD

**Issue by thedam** [fredsanto/coverageMaster#6]
Hi,

https://github.com/fredsanto/coverageMaster/blob/9679697f618e5b91158be25fdb6246571676537a/TOOLS/create_reference_cov.py#L34

```
python ../TOOLS/create_reference_cov.py cov_folder/ outp_folder/
Traceback (most recent call last):
  File "/coverageMaster//TOOLS/create_reference_cov.py", line 34, in <module>
    if not l:
NameError: name 'l' is not defined
```

Cheers

**Comment by thedam** [comment]
ps. also in the example you show how to create a text file:
 samtools depth -a -b <BED> <BAM> > <samplename>.cov
 
 but in the code indicates, that we have to work with binary files?
 open_f = [open(f, **"rb"**) for f in glob(dir + '/*cov')[:50]]

**Comment by Yaoming-Liu** [comment]
add "l = file.readline()" before "if not l"

**Comment by fredsanto** [comment]
Fixed now
