### ISSUE TITLE
Can Coverage Master Analysis both Somatic DNA or Germline?

### ISSUE THREAD

**Issue by vyomeshj209** [fredsanto/coverageMaster#9]
In the paper the test data looks like germline. Kindly please let me know if the analysis is performed on Somatic DNA (Solid Tumor) as well. 

Incase there are any validation study on Somatic DNA is it possible to share it ?
Looking forward for your response.

Thank you & Regards,
Vyomesh

**Comment by fredsanto** [comment]
coverageMaster works for somatic DNA too provided a sufficient purity (>90%).
